name: hysetter
channels:
- conda-forge
- nodefaults
dependencies:
- python >=3.10
- hysetter
# Examples
- flox
- ipykernel
- ipywidgets
- mapclassify
- matplotlib
- notebook
- numba
- numbagg
- pytest
- salib
- sceua
