name: hysetter-test
channels:
- conda-forge
- nodefaults
dependencies:
# HyRiver packages
- async-retriever >=0.16.1
- pygeoogc >=0.16.3
- pygeoutils >=0.16.3
- py3dep >=0.16.3
- pynhd >=0.16.3
- pygridmet >=0.16
- pydaymet >=0.16.3
- hydrosignatures >=0.16
- pynldas2 >=0.16
- pygeohydro >=0.16.3
# performance
- flox
- numba
- numbagg
# config
- pydantic
- pyyaml
# cli
- rich-click
# read/write
- pyogrio
- pyarrow
- gdal
# topo
- xarray-spatial
# soil
- pystac-client
- planetary-computer
- dask-expr
- boto3
# nhdplus
# - py7zr

# dev deps
- psutil
- pytest-cov
- pytest-xdist
- pytest-sugar
